Feat script file testing a user route configuration
meligys/routing pull request #12
Opened 2018-10-02 13:31 UTC by ArvsIndrarys

2018-10-02 13:34 UTC, mirza99 commented
How to use it ? It'll be nice to add a "how to test your config" in the readme.

2018-10-02 14:07 UTC, ArvsIndrarys commented
Done @mirza99

2018-10-02 14:25 UTC, mirza99 requested changes

2018-10-02 14:25 UTC, mirza99 commented on README.md
> +cd lib
It's `cd node_modules/@meligys/routing/lib`

2018-10-02 15:35 UTC, ArvsIndrarys commented
Changes done @mirza99

2018-10-03 08:32 UTC, mirza99 approved these changes

2018-10-03 08:32 UTC, merged